### ISSUE TITLE
9.3~9.5版本手册全文检索查找不到结果

### ISSUE THREAD

**Issue by ChenHuajun** [postgres-cn/website#8]
## 问题
9.3~9.5版本手册全文检索查找不到结果

## 原因
9.3~9.6版本的手册是HTML格式，不是well-formed XML（PG10以后是well-formed XML格式）。调用loadXML导入会失败，导致插入到数据库中得到记录不完整，没有提取到keywords。

```
	$doc = new DOMDocument();
	$content = file_get_contents('/var/www/html/docs/9.6/btree-gist.html');
	$doc->loadXML($content);
```

/var/www/html/application/logs/log-2020-10-04.php
```
ERROR - 2020-10-04 02:04:48 --> Severity: Warning  --> DOMDocument::loadXML(): Opening and ending tag mismatch: META line 27 and HEAD in Entity, line: 30 /var/www/html/application/controllers/v2/doc_search.php 113
```

/var/www/html/docs/9.6/btree-gist.html:27
```
CONTENT="text/html; charset=utf-8"><META
NAME="creation"
CONTENT="2020-10-03T18:03:22"></HEAD
```

注: 奇怪的是，以前9.3~9.6创建索引是成功的，最近更新索引失败了。怀疑虚机环境发生过变更，以前loadXML()检查不严格，现在严格了。

## 对策
建议修改html加载方式

/var/www/html/application/controllers/v2/doc_search.php
```
	$doc->loadXML($content);
==>
	$doc->loadHTML($content);
```

**Comment by doudou586** [comment]
已更新doc_search.php中相应内容为：
        if (in_array($version, ['9.3', '9.4', '9.5', '9.6'])) {
            $doc->loadHTML($content);
        }else 
			$doc->loadXML($content);
经华军验证，已解决问题了。
